en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Allergy Access. All Rights Reserved."
  title: "Allergy Access"
  params:
    description: "Allergy Access is a charitable organization dedicated to providing resources and support for individuals with allergies."
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Donate"
      link: "https://www.paypal.com/uk/home"
    footer_cta:
      text: "Donate"
      link: "https://www.paypal.com/uk/home"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/example-page/"
      weight: 1
    - identifier: "child-1"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 1
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "about"
    - identifier: "child-2"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 2
      post: "Aenean commodo ligula get dolor. Aenean massa."
      parent: "about"
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "about"
    - identifier: "demo-page"
      name: "Demo Page"
      url: "/demo-page/"
      weight: 2
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 3
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 4

