en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Allergy Access. All Rights Reserved."
  title: "Allergy Access"
  params:
    description: "Allergy Access is a charitable organization dedicated to providing resources and support for individuals with allergies."
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Donate"
      link: "https://www.paypal.com/uk/home"
    footer_cta:
      text: "Donate"
      link: "https://www.paypal.com/uk/home"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 2
    
    - identifier: "initatives"
      name: "Initatives"
      url: "/example-page/"
      weight: 1
    - identifier: "industry"
      name: "Industry"
      url: "/initiatives/industry/"
      weight: 1
      post: "What we do to promote allergy awareness in the food industry."
      parent: "initatives"
    - identifier: "restaurants"
      name: "Restaurants"
      url: "/initiatives/restaurants/"
      weight: 2
      post: "How we work with restaurants to promote allergy awareness."
      parent: "initatives"
    - identifier: "food banks"
      name: "Food Banks"
      url: "/initiatives/food-banks/"
      weight: 3
      post: "How we support food banks in promoting allergy awareness & supply."
      parent: "initatives"      
      
    - identifier: "blog"
      name: "Blog"
      url: "/example-page/"
      weight: 4
    - identifier: "recipes"
      name: "Recipes"
      url: "/blog/recipes/"
      weight: 1
      post: "Get tasty recipes that are allergy-friendly."
      parent: "blog"
    - identifier: "info"
      name: "Information"
      url: "/blog/infomation/"
      weight: 2
      post: "Get the latest information on allergies and food safety."
      parent: "blog"
    - identifier: "updates"
      name: "Updates"
      url: "/blog/updates/"
      weight: 3
      post: "Get the latest updates on our initiatives and events."
      parent: "blog"
    
    - identifier: "volunteering"
      name: "Volunteering"
      url: "/volunteering/"
      weight: 5
    
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 3
    
