en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Allergy Access. All Rights Reserved."
  title: "Allergy Access"
  params:
    description: "Allergy Access is a charitable organization dedicated to providing resources and support for individuals with allergies."
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Donate"
      link: "https://www.paypal.com/uk/home"
    footer_cta:
      text: "Donate"
      link: "https://www.paypal.com/uk/home"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/"
      weight: 1
    - identifier: "about us"
      name: "About Us"
      url: "/about/about-us/"
      weight: 1
      post: "Get involved and make a difference in the allergy community."
      parent: "about"
    - identifier: "volunteering"
      name: "Volunteering"
      url: "/about/volunteering/"
      weight: 2
      post: "Get involved and make a difference in the allergy community."
      parent: "about"
        
    - identifier: "initatives"
      name: "Initatives"
      url: "/example-page/"
      weight: 2
    - identifier: "industry"
      name: "Industry"
      url: "/initiatives/industry/"
      weight: 1
      post: "What we do to promote allergy awareness in the food industry."
      parent: "initatives"
    - identifier: "restaurants"
      name: "Restaurants"
      url: "/initiatives/restaurants/"
      weight: 2
      post: "How we work with restaurants to promote allergy awareness."
      parent: "initatives"
    - identifier: "food banks"
      name: "Food Banks"
      url: "/initiatives/food-banks/"
      weight: 3
      post: "How we support food banks in promoting allergy awareness & supply."
      parent: "initatives"      

    - identifier: "partners"
      name: "Partners"
      url: "/partners/"
      weight: 3

    - identifier: "blog"
      name: "Blog"
      url: "/example-page/"
      weight: 4
    - identifier: "advice"
      name: "Advice"
      url: "/blog/advice/"
      weight: 1
      post: "Get the latest advice and tips on allergies and food safety."
      parent: "blog"
    - identifier: "updates"
      name: "Updates"
      url: "/blog/updates/"
      weight: 2
      post: "Get the latest updates on our initiatives and events."
      parent: "blog"
    
    - identifier: "recipes"
      name: "Recipes"
      url: "/"
      weight: 6
    - identifier: "nut free"
      name: "Nut Free"
      url: "/recipes/nut-free/"
      weight: 1
      post: "Nut free recipes for everyone."
      parent: "recipes"
    - identifier: "gluten free"
      name: "Gluten Free"
      url: "/recipes/gluten-free/"
      weight: 2
      post: "Gluten free recipes for everyone."
      parent: "recipes"
    
    
    
